### ISSUE TITLE
Schedule Event page

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/gc_scoreboard#8]
### Summary

Complete the schedule new event page as shown in the design and cover all possible cases

**Comment by vrrao01** [comment]
@mauryakshitij @tanisha-salvi Try keeping the page similar to the ResultForm that already made. You can reuse the dropdown and text fields or improve them. 
Also, make sure the same form can serve as both Add Event and Edit Event form. Have an EventStore(see ResultStore) that maintains the state.
