### ISSUE TITLE
Add Standing Form Bug

### ISSUE THREAD

**Issue by vrrao01** [swciitg/gc_scoreboard#81]
### Description

Can't enter primary score in add standings form. Keyboard automatically collapses. 
Emulator: Nexus 4

### Reproduction steps

```bash
1. Login as Admin
2. Add Standings
```

### Screenshots

[Screencast from 12-01-23 02:34:01 PM IST.webm](https://user-images.githubusercontent.com/75874394/212024196-5c2d2d69-7167-4b47-97ba-8466c371c300.webm)

### Platform

Android

**Comment by vrrao01** [comment]
Same issue in add result form while entering primary score.
[Screencast from 12-01-23 03:04:17 PM IST.webm](https://user-images.githubusercontent.com/75874394/212031072-5c0f67e6-8bb9-49c7-a45e-aa711542e81c.webm)

**Comment by SWCIITGWeb** [comment]
![image](https://user-images.githubusercontent.com/102794077/212076348-1b68a5c4-03a2-4212-b56c-0ff5d96bb526.png)
Correct the renderflow
